on: [pull_request, push]

jobs:
  self_test:
    name: Action Self Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run the Action
        uses: ./
        id: netlify
        with:
          access_token: ${{ secrets.NETLIFY_TOKEN }}
          account_slug: "lunelson"
          site_name: "lunelson-xyz"
          commit_ref: "530d6d3b3de314ee7079ca1900713abab893e22f"
